services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper1
    hostname: zookeeper1
    container_name: zookeeper1
    restart: on-failure
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:7.6.1
    ports:
      - "9091:9091"
    restart: on-failure
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka1:19091,LISTENER_EXTERNAL://localhost:9091
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper1

  kafka2:
    image: confluentinc/cp-kafka:7.6.1
    ports:
      - "9092:9092"
    restart: on-failure      
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka2:19092,LISTENER_EXTERNAL://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
      KAFKA_BROKER_ID: 2
    depends_on:
      - zookeeper1

  kafka3:
    image: confluentinc/cp-kafka:7.6.1
    ports:
      - "9093:9093"
    restart: on-failure
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka3:19093,LISTENER_EXTERNAL://localhost:9093
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
      KAFKA_BROKER_ID: 3
    depends_on:
      - zookeeper1

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password