@Producer_HostAddress = https://localhost:5001
@Consumer_HostAddress = https://localhost:5003

POST {{Producer_HostAddress}}/messages?count=1
Accept: application/json

###
GET {{Producer_HostAddress}}/outbox
Accept: application/json

###
GET {{Consumer_HostAddress}}/messages
Accept: application/json


###
DELETE {{Consumer_HostAddress}}/messages/cleanup
Accept: application/json
